[package]
name = "fdk-mqa-url-checker"
version = "0.1.0"
edition = "2021"
authors = ["Jeff Reiffers <jeff@ouvir.no>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
apache-avro = "0.14.0"
cached = "0.43.0"
chrono = "0.4.19"
clap = { version = "4.1.11", features = ["derive"] }
env_logger = "0.8.4"
futures = "0.3"
http = "0.2.6"
lazy_static = "1.4.0"
log = "0.4"
oxigraph = "0.3.1"
prometheus = "0.13.1"
rand = "0.8.4"
rdkafka = { version = "0.29", features = ["cmake-build"] }
schema_registry_converter = { version = "3.1.0", features = ["avro", "blocking"] }
reqwest = { version = "0.10.10", features = ["blocking"] }
serde = "1.0.141"
serde_derive = "1.0.141"
thiserror = "1.0.31"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber =  { version = "0.3.11", features = ["json"] }
url = "2.2.2"
uuid = { version = "1.0.0", features = ["v4"] }
